// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'ar'
	| 'de'
	| 'en'
	| 'fr'
	| 'hi'
	| 'it'
	| 'ja'
	| 'ko'
	| 'nl'
	| 'pl'
	| 'ru'
	| 'tr'
	| 'zh'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	nav: {
		/**
		 * H​o​m​e
		 */
		home: string
		/**
		 * A​l​l
		 */
		all: string
		/**
		 * P​e​r​s​o​n​a​l
		 */
		personal: string
		/**
		 * W​o​r​k
		 */
		work: string
	}
}

export type TranslationFunctions = {
	nav: {
		/**
		 * Home
		 */
		home: () => LocalizedString
		/**
		 * All
		 */
		all: () => LocalizedString
		/**
		 * Personal
		 */
		personal: () => LocalizedString
		/**
		 * Work
		 */
		work: () => LocalizedString
	}
}

export type Formatters = {}
