// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * H​i​ ​{​n​a​m​e​}​!​ ​P​l​e​a​s​e​ ​f​k​ ​o​f​f
	 * @param {string} name
	 */
	HI: RequiredParams<'name'>
	/**
	 * R​e​c​e​n​t​s
	 */
	RECENTS: string
}

export type TranslationFunctions = {
	/**
	 * Hi {name}! Please fk off
	 */
	HI: (arg: { name: string }) => LocalizedString
	/**
	 * Recents
	 */
	RECENTS: () => LocalizedString
}

export type Formatters = {}
